Ecommerce/Models/Brand.cs
using System.ComponentModel.DataAnnotations;


namespace Ecommerce.Models
{
    public class Brand
    {
        [Key]
        public int Id { get; set; }

        [Display(Name="عنوان")]
        [Required(ErrorMessage = "فیلد عنوان نمیتواند خالی باشد.")]
        public string Title { get; set; }
    }
}

Ecommerce/Areas/Admin/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Helpers.OptionEnums;
using Ecommerce.Models;
using Ecommerce.Net;
using Ecommerce.Net.OptionEnums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BrandController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _IServiceProvider;

        public BrandController(ApplicationDbContext context,IServiceProvider IServiceProvider)
        {
            _context = context;
            _IServiceProvider = IServiceProvider;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _context.Brands.ToListAsync();
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> AddEditBrand(int id)
        {
            var Brand = new Brand();
            if(id !=0)
            {
                using (var db = _IServiceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    Brand = await _context.Brands.Where(b => b.Id == id).SingleOrDefaultAsync();
                    if(Brand==null)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }

            return PartialView("AddEditBrand", Brand);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditBrand(int Id,Brand model, string redirecturl)
        {
            if(ModelState.IsValid)
            {
                if(Id==0)
                {
                   using(var db=_IServiceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        db.Brands.Add(model);
                        await db.SaveChangesAsync();
                    }
                    TempData["Notif"] = Notification.ShowNotif(MessageType.Add, type:ToastType.green);
                    return PartialView("_Succefullyresponse", redirecturl);
                }
                else
                {
                    using (var db = _IServiceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        db.Brands.Update(model);
                        await db.SaveChangesAsync();
                    }
                    TempData["Notif"] = Notification.ShowNotif(MessageType.Edit, type: ToastType.blue);
                    return PartialView("_Succefullyresponse", redirecturl);
                }
            }
            else
            {
                if(Id==0)
                {
                    TempData["Notif"] = Notification.ShowNotif(MessageType.addError, type: ToastType.yellow);

                }
                else
                {
                    TempData["Notif"] = Notification.ShowNotif(MessageType.editError, type: ToastType.yellow);
                }
            }

            return PartialView("AddEditBrand", model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteBrand(int Id)
        {
            var Brand = new Brand();
            if(Id!=0)
            {
                using (var db = _IServiceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    Brand = await _context.Brands.Where(b => b.Id == Id).SingleOrDefaultAsync();
                    if(Brand==null)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return PartialView("DeleteBrand",Brand.Title);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteBrand(int Id, string redirecturl)
        {
            if(ModelState.IsValid)
            {
                using (var db = _IServiceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    var model = await _context.Brands.Where(b => b.Id == Id).SingleOrDefaultAsync();
                    db.Brands.Remove(model);
                  await db.SaveChangesAsync();
                }
                TempData["Notif"] = Notification.ShowNotif(MessageType.Delete, type: ToastType.red);
                return PartialView("_Succefullyresponse", redirecturl);
            }
            else
            {
                TempData["Notif"] = Notification.ShowNotif(MessageType.deleteError, type:ToastType.red);
                return RedirectToAction("Index");
            }

        }
    }
}

Ecommerce/Areas/Admin/Views/Brand/AddEditBrand.cshtml
@model Ecommerce.Models.Brand
@using Ecommerce.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Ecommerce


<form asp-controller="Brand" asp-action="AddEditBrand" id="addeditBrand" data-ajax="true" data-ajax-method="post"
      data-ajax-update="#addeditBrand" data-ajax-mode="replace">

    @*header*@
    @if (Model.Id != 0)
    {
    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "ویرایش برند" })
    }
    else
    {
    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "افزودن برند" })
    }

    @*body*@
    <div class="modal-body form-horizontal">

        <div class="row">
            <div class="form-group">
                <label asp-for="Title" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group hidden">
                <label asp-for="Id" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Id" class="form-control" />
                </div>
            </div>

            <input type="hidden" name="redirecturl" value="@Url.Action("index","Brand")" />

        </div>
    </div>

    @*footer*@
    @if (Model.Id != 0)
    {
    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "ویرایش برند" })
    }
    else
    {
    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "افزودن برند" })
    }

</form>

Ecommerce/Areas/Admin/Views/Brand/DeleteBrand.cshtml
@model string
@using Ecommerce.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Ecommerce

<form asp-controller="Brand" asp-action="DeleteBrand">

    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "حذف برند" })

    <div class="modal-body form-horizontal">
        آیا از حذف  @Model مطمئن هستید؟
    </div>

    <input type="hidden" name="redirecturl" value="@Url.Action("index","Brand")" />


    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "حذف " })

</form>

Ecommerce/Areas/Admin/Views/Brand/Index.cshtml
@model IEnumerable<Ecommerce.Models.Brand>
@using Ecommerce.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Ecommerce

@{
    ViewData["Title"] = "برند ها";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="color:white;text-align:center" class=@TempData["css"]>
    @if (TempData["notice"] != null)
    {
        <p>@TempData["notice"]</p>
    }
</div>
<div class="layout-content-body">
    <div class="row gutter-xs">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-actions">
                        <button type="button" class="card-action card-toggler" title="Collapse"></button>
                        <button type="button" class="card-action card-reload" title="Reload"></button>
                        <button type="button" class="card-action card-remove" title="Remove"></button>
                    </div>
                    <strong>برند ها</strong>
                </div>

                <div class="card-body">

                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="md-form-group md-label-floating col-md-6">
                            <input class="md-form-control" type="text" name="name" id="serachInput" spellcheck="false" required="" aria-required="true">
                            <label class="md-control-label">جستجو</label>
                        </div>
                    </div>
                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="margin-top">
                            <div class="col-xs-6 col-md-6">
                                <a class="btn btn-primary marginbutoom" id="showBrand" data-toggle="modal" asp-action="AddEditBrand"
                                   data-target="#modal-action-Brand">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    افزودن برند جدید
                                </a>
                            </div>
                        </div>
                    </div>
                    <table id="example" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>کد</th>
                                <th>@Html.DisplayNameFor(model => model.Title)</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 1;
                                foreach (var item in Model)
                                {

                                    <tr>
                                        <td>@(i++)</td>
                                        <td>@item.Title</td>



                                        <td>
                                            <a class="btn btn-info" id="editagency" data-toggle="modal" asp-action="AddEditBrand"
                                               data-target="#modal-action-Brand" asp-route-Id="@item.Id">
                                                <i class="glyphicon glyphicon-pencil"></i>
                                                ویرایش
                                            </a>

                                            <a class="btn btn-danger" id="showagency" data-toggle="modal" asp-action="DeleteBrand"
                                               data-target="#modal-action-Brand" asp-route-Id="@item.Id">
                                                <i class="glyphicon glyphicon-trash"></i>
                                                حذف
                                            </a>

                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="progress" class="addModal">
    <div class="addCenter">
        <img src="~/Content/loading.gif" />
    </div>
</div>
<div id="infoModalAlertColored" tabindex="-1" role="dialog" class="modal fade">

</div>
<div id="successModalAlert" tabindex="-1" role="dialog" class="modal fade">

</div>

@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-Brand", Size = ModalSize.Medium })

@section Scripts{
    <script src="~/js/modal-js/Brand-indx.js"></script>
}