Ecommerce/Models/SelectItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Ecommerce.Models
{
    public class SelectItem
    {
        public int Id { get; set; }

        public int IdSelectGroup { get; set; }
        [ForeignKey("IdSelectGroup")]
        public virtual SelectGroup SelectGroupList { get; set; }

        public string Title { get; set; }
    }
}

Ecommerce/Models/ViewModels/AddEditSelectItemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Ecommerce.Models.ViewModels
{
    public class AddEditSelectItemViewModel
    {
        public int Id { get; set; }

        [Display(Name = "انتخاب آیتم")]
        public int IdSelectGroup { get; set; }

        public List<SelectListItem> SelectGroupListItems { get; set; }

        [Display(Name = "عنوان")]
        public string Title { get; set; }
    }
}

Ecommerce/Models/ViewModels/SelectItemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Ecommerce.Models.ViewModels
{
    public class SelectItemViewModel
    {
        public int Id { get; set; }

        public int IdSelectGroup { get; set; }

        [Display(Name = "گروه آیتم")]
        public string SelectGroupTitle { get; set; }

        [Display(Name = "عنوان")]
        public string Title { get; set; }
    }
}

Ecommerce/Areas/Admin/Controllers/SelectItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Helpers.OptionEnums;
using Ecommerce.Models;
using Ecommerce.Models.ViewModels;
using Ecommerce.Net;
using Ecommerce.Net.OptionEnums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SelectItemController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _serviceProvider;

        public SelectItemController(ApplicationDbContext context, IServiceProvider serviceProvider)
        {
            _context = context;
            _serviceProvider = serviceProvider;
        }

        public async Task<IActionResult> Index()
        {
            var query = await (from si in _context.SelectItems
                join Sg in _context.SelectGroups on si.IdSelectGroup equals Sg.Id
                select new SelectItemViewModel
                {
                    Id = si.Id,
                    IdSelectGroup = si.IdSelectGroup,
                    SelectGroupTitle = Sg.Title,
                    Title = si.Title
                }).ToListAsync();

            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> AddEditSelectItem(int id)
        {

            AddEditSelectItemViewModel model = new AddEditSelectItemViewModel();
            model.SelectGroupListItems = await _context.SelectGroups.Select(c => new SelectListItem()
            {
                Text = c.Title,
                Value = c.Id.ToString()
            }).ToListAsync();

            if (id != 0)
            {
                using (_serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    SelectItem SelectItem = await _context.SelectItems.Where(a => a.Id == id).SingleOrDefaultAsync();
                    if (SelectItem != null)
                    {
                        model.Id = SelectItem.Id;
                        model.Title = SelectItem.Title;
                        model.IdSelectGroup = SelectItem.IdSelectGroup;
                    }

                }
            }

            return PartialView("AddEditSelectItem", model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditSelectItem(int Id, AddEditSelectItemViewModel model, string redirectUrl)
        {
            if (ModelState.IsValid)
            {
                if (Id == 0)
                {
                    using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        SelectItem SelectItemModel = AutoMapper.Mapper.Map<AddEditSelectItemViewModel, SelectItem>(model);
                        db.SelectItems.Add(SelectItemModel);
                        await db.SaveChangesAsync();
                    }

                    TempData["Notif"] = Notification.ShowNotif(MessageType.Add, type: ToastType.green);

                    return PartialView("_Succefullyresponse", redirectUrl);
                }
                else
                {
                    using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        SelectItem SelectItemModel = AutoMapper.Mapper.Map<AddEditSelectItemViewModel, SelectItem>(model);
                        db.SelectItems.Update(SelectItemModel);
                        await db.SaveChangesAsync();
                    }

                    TempData["Notif"] = Notification.ShowNotif(MessageType.Edit, type: ToastType.blue);

                    return PartialView("_Succefullyresponse", redirectUrl);
                }
            }

            if (Id == 0)
            {
                TempData["Notif"] = Notification.ShowNotif(MessageType.addError, type: ToastType.yellow);
            }
            else
            {
                TempData["Notif"] = Notification.ShowNotif(MessageType.editError, type: ToastType.yellow);
            }

            model.SelectGroupListItems = await _context.SelectGroups.Select(c => new SelectListItem()
            {
                Text = c.Title,
                Value = c.Id.ToString()
            }).ToListAsync();

            return PartialView("AddEditSelectItem", model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteSelectItem(int Id)
        {
            var SelectItem = new SelectItem();
            using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
            {
                SelectItem = await db.SelectItems.Where(a => a.Id == Id).SingleOrDefaultAsync();
                if (SelectItem == null)
                {
                    return RedirectToAction("Index");
                }
            }

            return PartialView("DeleteSelectItem", SelectItem.Title);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteSelectItem(int id, string redirectUrl)
        {
            if (ModelState.IsValid)
            {
                using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    var SelectItem = await db.SelectItems.Where(a => a.Id == id).SingleOrDefaultAsync();

                    db.SelectItems.Remove(SelectItem);
                    await db.SaveChangesAsync();

                    TempData["Notif"] = Notification.ShowNotif(MessageType.Delete, type: ToastType.red);

                    return PartialView("_Succefullyresponse", redirectUrl);
                }
            }

            TempData["Notif"] = Notification.ShowNotif(MessageType.deleteError, type: ToastType.yellow);

            return RedirectToAction("Index");

        }
    }
}

Ecommerce/Areas/Admin/Views/SelectItem/AddEditSelectItem.cshtml
@model Ecommerce.Models.ViewModels.AddEditSelectItemViewModel
@using Ecommerce.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Ecommerce


<form asp-controller="SelectItem" asp-action="AddEditSelectItem" id="addeditSelectItem" data-ajax="true" data-ajax-method="post"
      data-ajax-update="#addeditSelectItem" data-ajax-mode="replace">

    @*header*@
    @if (Model.Id != 0)
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "ویرایش " })
    }
    else
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "افزودن " })
    }

    @*body*@
    <div class="modal-body form-horizontal">

        <div class="row">
            <div class="form-group">
                <label asp-for="Title" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="IdSelectGroup" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <select asp-for="IdSelectGroup" asp-items="@Model.SelectGroupListItems" class="form-control">
                        <option value="" disabled="disabled" selected="selected">انتخاب استان</option>
                    </select>
                </div>
            </div>

            <div class="form-group hidden">
                <label asp-for="Id" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Id" class="form-control" />
                </div>
            </div>

            <input type="hidden" name="redirectUrl" value="@Url.Action("index","SelectItem")" />

        </div>
    </div>

    @*footer*@
    @if (Model.Id != 0)
    {
        @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "ویرایش" })
    }
    else
    {
        @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "افزودن" })
    }

</form>

Ecommerce/Areas/Admin/Views/SelectItem/DeleteSelectItem.cshtml
@model string
@using Ecommerce.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Ecommerce

<form asp-controller="SelectItem" asp-action="DeleteSelectItem">

    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "حذف " })

    <div class="modal-body form-horizontal">
        آیا از حذف  @Model مطمئن هستید؟
    </div>

    <input type="hidden" name="redirectUrl" value="@Url.Action("index","SelectItem")" />


    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "حذف " })

</form>

Ecommerce/Areas/Admin/Views/SelectItem/Index.cshtml
@model IEnumerable<Ecommerce.Models.ViewModels.SelectItemViewModel>
@using Ecommerce.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Ecommerce

@{
    ViewData["Title"] = "آیتم ها";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="color:white;text-align:center" class=@TempData["css"]>
    @if (TempData["notice"] != null)
    {
        <p>@TempData["notice"]</p>
    }
</div>
<div class="layout-content-body">
    <div class="row gutter-xs">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-actions">
                        <button type="button" class="card-action card-toggler" title="Collapse"></button>
                        <button type="button" class="card-action card-reload" title="Reload"></button>
                        <button type="button" class="card-action card-remove" title="Remove"></button>
                    </div>
                    <strong>فیلد</strong>
                </div>

                <div class="card-body">

                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="md-form-group md-label-floating col-md-6">
                            <input class="md-form-control" type="text" name="name" id="serachInput" spellcheck="false" required="" aria-required="true">
                            <label class="md-control-label">جستجو</label>
                        </div>
                    </div>
                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="margin-top">
                            <div class="col-xs-6 col-md-6">
                                <a class="btn btn-primary marginbutoom" id="showaselectitem" data-toggle="modal" asp-action="AddEditselectitem"
                                   data-target="#modal-action-selectitem">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    افزودن فیلد جدید
                                </a>
                            </div>
                        </div>
                    </div>
                    <table id="example" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>کد</th>
                                <th>@Html.DisplayNameFor(model => model.Title)</th>
                                <th>@Html.DisplayNameFor(model => model.SelectGroupTitle)</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 1;
                                foreach (var item in Model)
                                {

                                    <tr>
                                        <td>@(i++)</td>
                                        <td>@item.Title</td>

                                        <td>@item.SelectGroupTitle</td>


                                        <td>
                                            <a class="btn btn-info" id="editselectitem" data-toggle="modal" asp-action="AddEditselectitem"
                                               data-target="#modal-action-selectitem" asp-route-Id="@item.Id">
                                                <i class="glyphicon glyphicon-pencil"></i>
                                                ویرایش
                                            </a>

                                            <a class="btn btn-danger" id="showselectitem" data-toggle="modal" asp-action="Deleteselectitem"
                                               data-target="#modal-action-selectitem" asp-route-Id="@item.Id">
                                                <i class="glyphicon glyphicon-trash"></i>
                                                حذف
                                            </a>

                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="progress" class="addModal">
    <div class="addCenter">
        <img src="~/Content/loading.gif" />
    </div>
</div>
<div id="infoModalAlertColored" tabindex="-1" role="dialog" class="modal fade">

</div>
<div id="successModalAlert" tabindex="-1" role="dialog" class="modal fade">

</div>

@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-selectitem", Size = ModalSize.Medium })

@section Scripts{
    <script src="~/js/modal-js/selectitem-index.js"></script>
}