Ecommerce/Models/Offer.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace Ecommerce.Models
{
    public class Offer
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "عنوان")]
        [Required(ErrorMessage = "فیلد عنوان نمیتواند خالی باشد.")]
        public string Title { get; set; }

        [Display(Name = "تاریخ شروع")]
        public DateTime StartDate { get; set; }

        [Display(Name = "تاریخ پایان")]
        public DateTime EndDate { get; set; }

        [Display(Name = "فعال")]
        public bool IsActiv { get; set; }
    }
}

Ecommerce/Areas/Admin/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Helpers.OptionEnums;
using Ecommerce.Models;
using Ecommerce.Net;
using Ecommerce.Net.OptionEnums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using static Microsoft.AspNetCore.Hosting.Internal.HostingApplication;

namespace Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class OfferController : Controller
    {
        private readonly ApplicationDbContext _Context;
        public readonly IServiceProvider _IServiceProvider;

        public OfferController(ApplicationDbContext context, IServiceProvider IServiceProvider)
        {
            _IServiceProvider = IServiceProvider;
            _Context = context;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _Context.Offers.ToListAsync();
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> AddEditOffer(int Id)
        {
            var offer = new Offer();
            if (Id != 0)
            {
                using (var db = _IServiceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    offer = await _Context.Offers.Where(b => b.Id == Id).SingleOrDefaultAsync();
                    if (offer == null)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }

            return PartialView("AddEditOffer", offer);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditOffer(int Id, Offer model, string redirecturl)
        {
            if (ModelState.IsValid)
            {
                if (Id == 0)
                {
                    using (var db = _IServiceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        db.Offers.Add(model);
                        await db.SaveChangesAsync();
                    }
                    TempData["Notif"] = Notification.ShowNotif(MessageType.Add, type: ToastType.green);
                    return PartialView("_Succefullyresponse", redirecturl);
                }
                else
                {
                    using (var db = _IServiceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        db.Offers.Update(model);
                        await db.SaveChangesAsync();
                    }
                    TempData["Notif"] = Notification.ShowNotif(MessageType.Edit, type: ToastType.blue);
                    return PartialView("_Succefullyresponse", redirecturl);
                }
            }
            else
            {
                if (Id == 0)
                {
                    TempData["Notif"] = Notification.ShowNotif(MessageType.editError, type: ToastType.yellow);

                }
                else
                {
                    TempData["Notif"] = Notification.ShowNotif(MessageType.editError, type: ToastType.yellow);
                }
            }

            return PartialView("AddEditOffer", model);
        }
        [HttpGet]
        public async Task<IActionResult> DeleteOffer(int Id)
        {
            var offer = new Offer();
            if (Id != 0)
            {
                using (var db = _IServiceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    offer = await _Context.Offers.Where(b => b.Id == Id).SingleOrDefaultAsync();
                    if (offer == null)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }

            return PartialView("DeleteOffer",offer.Title);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteOffer(int Id, string redirecturl)
        {
            if (ModelState.IsValid)
            {
                using (var db = _IServiceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    var model = await _Context.Offers.Where(b => b.Id == Id).SingleOrDefaultAsync();
                    db.Offers.Remove(model);
                    await db.SaveChangesAsync();
                }
                TempData["Notif"] = Notification.ShowNotif(MessageType.Delete, type: ToastType.red);
                return PartialView("_Succefullyresponse", redirecturl);
            }
            else
            {
                TempData["Notif"] = Notification.ShowNotif(MessageType.deleteError, type: ToastType.red);
                return RedirectToAction("Index");
            }
        }
    }
}

Ecommerce/Areas/Admin/Views/Offer/AddEditOffer.cshtml
@model Ecommerce.Models.Offer
@using Ecommerce.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Ecommerce


<form asp-controller="Offer" asp-action="AddEditOffer" id="addeditoffer" data-ajax="true" data-ajax-method="post"
      data-ajax-update="#addeditoffer" data-ajax-mode="replace">

    @*header*@
    @if (Model.Id != 0)
    {
    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "ویرایش تخفیف" })
    }
    else
    {
    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "افزودن تخفیف" })
    }

    @*body*@
    <div class="modal-body form-horizontal">
        <div class="row">
            <div class="form-group">
                <label asp-for="Title" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="StartDate" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="EndDate" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="IsActiv" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="IsActiv" class="form-control" />
                    <span asp-validation-for="IsActiv" class="text-danger"></span>
                </div>
            </div>

           


            <div class="form-group hidden">
                <label asp-for="Id" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Id" class="form-control" />
                </div>
            </div>

            <input type="hidden" name="redirecturl" value="@Url.Action("Index","Offer")" />

        </div>
    </div>

    @*footer*@
    @if (Model.Id != 0)
    {
    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "ویرایش تخفیف" })
    }
    else
    {
    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "افزودن تخفیف" })
    }

</form>

Ecommerce/Areas/Admin/Views/Offer/DeleteOffer.cshtml
@model string
@using Ecommerce.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Ecommerce

<form asp-controller="Offer" asp-action="DeleteOffer">

    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "حذف تخفیف" })

    <div class="modal-body form-horizontal">
        آیا از حذف  @Model مطمئن هستید؟
    </div>

    <input type="hidden" name="redirecturl" value="@Url.Action("index","Offer")" />


    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "حذف " })

</form>

Ecommerce/Areas/Admin/Views/Offer/Index.cshtml
@model IEnumerable<Ecommerce.Models.Offer>
@using Ecommerce.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Ecommerce

@{
    ViewData["Title"] = "تخفیفات";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="color:white;text-align:center" class=@TempData["css"]>
    @if (TempData["notice"] != null)
    {
        <p>@TempData["notice"]</p>
    }
</div>
<div class="layout-content-body">
    <div class="row gutter-xs">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-actions">
                        <button type="button" class="card-action card-toggler" title="Collapse"></button>
                        <button type="button" class="card-action card-reload" title="Reload"></button>
                        <button type="button" class="card-action card-remove" title="Remove"></button>
                    </div>
                    <strong>تخفیفات</strong>
                </div>

                <div class="card-body">

                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="md-form-group md-label-floating col-md-6">
                            <input class="md-form-control" type="text" name="name" id="serachInput" spellcheck="false" required="" aria-required="true">
                            <label class="md-control-label">جستجو</label>
                        </div>
                    </div>
                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="margin-top">
                            <div class="col-xs-6 col-md-6">
                                <a class="btn btn-primary marginbutoom" id="showOffer" data-toggle="modal" asp-action="AddEditOffer"
                                   data-target="#modal-action-Offer">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    افزودن تخفیفات جدید
                                </a>
                            </div>
                        </div>
                    </div>
                    <table id="example" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>کد</th>
                                <th>@Html.DisplayNameFor(model => model.Title)</th>
                                <th>@Html.DisplayNameFor(model => model.StartDate)</th>
                                <th>@Html.DisplayNameFor(model => model.EndDate)</th>
                                <th>@Html.DisplayNameFor(model => model.IsActiv)</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 1;
                                foreach (var item in Model)
                                {

                                    <tr>
                                        <td>@(i++)</td>
                                        <td>@item.Title</td>
                                        <td>@item.StartDate</td>
                                        <td>@item.EndDate</td>
                                        <td>@item.IsActiv</td>


                                        <td>
                                            <a class="btn btn-info" id="editagency" data-toggle="modal" asp-action="AddEditOffer"
                                               data-target="#modal-action-Offer" asp-route-Id="@item.Id">
                                                <i class="glyphicon glyphicon-pencil"></i>
                                                ویرایش
                                            </a>

                                            <a class="btn btn-danger" id="showagency" data-toggle="modal" asp-action="DeleteOffer"
                                               data-target="#modal-action-Offer" asp-route-Id="@item.Id">
                                                <i class="glyphicon glyphicon-trash"></i>
                                                حذف
                                            </a>

                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="progress" class="addModal">
    <div class="addCenter">
        <img src="~/Content/loading.gif" />
    </div>
</div>
<div id="infoModalAlertColored" tabindex="-1" role="dialog" class="modal fade">

</div>
<div id="successModalAlert" tabindex="-1" role="dialog" class="modal fade">

</div>

@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-Offer", Size = ModalSize.Medium })

@section Scripts{
    <script src="~/js/modal-js/Offer-index.js"></script>
}