Ecommerce/Models/ApplicationRole.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace Ecommerce.Models
{
    public class ApplicationRole : IdentityRole
    {
        public string Description { get; set; }

        public virtual ICollection<ApplicationUser> User { get; set; }
    }
}

Ecommerce/Models/ViewModels/ApplicationRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Ecommerce.Models.ViewModels
{
    public class ApplicationRoleViewModel
    {
        public string Id { get; set; }

        [Display(Name = "عنوان نقش")]
        [Required(ErrorMessage = "لطفا عنوان نقش را وارد کنید")]
        public string Name { get; set; }

        [Display(Name = "توضیحات نقش")]
        [Required(ErrorMessage = "لطفا توضیحات نقش را وارد کنید")]
        public string Description { get; set; }
    }
}

Ecommerce/Areas/Admin/Controllers/ApplicationRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Models;
using Ecommerce.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ApplicationRoleController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;

        public ApplicationRoleController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            List<ApplicationRoleViewModel> model = new List<ApplicationRoleViewModel>();
            model = _roleManager.Roles.Select(r => new ApplicationRoleViewModel
            {
                Id = r.Id,
                Name = r.Name,
                Description = r.Description

            }).ToList();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddEditApplicationRole(string Id)
        {
            ApplicationRoleViewModel model = new ApplicationRoleViewModel();
            if (!string.IsNullOrEmpty(Id))
            {
                ApplicationRole applicationRole = await _roleManager.FindByIdAsync(Id);

                if (applicationRole != null)
                {
                    model.Id = applicationRole.Id;
                    model.Name = applicationRole.Name;
                    model.Description = applicationRole.Description;
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }

            return PartialView("AddEditApplicationRole", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditApplicationRole(string Id, ApplicationRoleViewModel model, string redirecturl)
        {
            if (ModelState.IsValid)
            {
                bool isExist = !String.IsNullOrEmpty(Id);
                ApplicationRole applicationRole = isExist ? await _roleManager.FindByIdAsync(Id) :
                    new ApplicationRole //insert
                    {

                    };

                applicationRole.Name = model.Name;
                applicationRole.Description = model.Description;

                IdentityResult roleresult = isExist ? await _roleManager.UpdateAsync(applicationRole) :
                    await _roleManager.CreateAsync(applicationRole);

                if (roleresult.Succeeded)
                {
                    return PartialView("_Succefullyresponse", redirecturl);
                }
            }
            return PartialView("AddEditApplicationRole", model);

        }

        [HttpGet]
        public async Task<IActionResult> DeleteRole(string id)
        {
            string name = string.Empty;
            if (!String.IsNullOrEmpty(id))
            {
                ApplicationRole ar = await _roleManager.FindByIdAsync(id);
                if (ar != null)
                {
                    name = ar.Name;
                }
            }
            return PartialView("DeleteRole", name);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id, IFormCollection form)
        {
            if (!string.IsNullOrEmpty(id))
            {
                ApplicationRole ar = await _roleManager.FindByIdAsync(id);
                if (ar != null)
                {
                    IdentityResult roleresult = _roleManager.DeleteAsync(ar).Result;
                    if (roleresult.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View("Index");
        }
    }
}

Ecommerce/Areas/Admin/Views/ApplicationRole/AddEditApplicationRole.cshtml
@model Ecommerce.Models.ViewModels.ApplicationRoleViewModel
@using Ecommerce.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Ecommerce

<form asp-controller="ApplicationRole" asp-action="AddEditApplicationRole" id="addeditrole" data-ajax="true" data-ajax-method="post"
      data-ajax-update="#addeditrole" data-ajax-mode="replace">

    @*header*@

    @if (!string.IsNullOrEmpty(Model.Id))
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "ویرایش نقش سیستمی" })
    }
    else
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "افزودن نقش سیستمی" })
    }





    @*body*@
    <div class="modal-body form-horizontal">
        <div class="row">
            <div class="form-group">
                <label asp-for="Name" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group hidden">
                <label asp-for="Id" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Id" class="form-control" />
                </div>
            </div>

            <input type="hidden" name="redirecturl" value="@Url.Action("index","ApplicationRole")" />

        </div>


    </div>

    @*footer*@
    @if (!string.IsNullOrEmpty(Model.Id))
    {
        @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "ویرایش نقش" })
    }
    else
    {
        @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "افزودن نقش" })
    }


</form>

Ecommerce/Areas/Admin/Views/ApplicationRole/DeleteRole.cshtml
@model string
@using Ecommerce.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, LibraryProject

<form asp-controller="ApplicationRole" asp-action="DeleteRole">

    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "حذف نقش" })

    <div class="modal-body form-horizontal">
        آیا از حذف نقش  @Model مطمئن هستید؟ 
    </div>


    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "حذف نقشُ" })

</form>

Ecommerce/Areas/Admin/Views/ApplicationRole/Index.cshtml
@model IEnumerable<Ecommerce.Models.ViewModels.ApplicationRoleViewModel>
@using Ecommerce.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Ecommerce


@{
    ViewData["Title"] = "نقش ها";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="color:white;text-align:center" class=@TempData["css"]>
    @if (TempData["notice"] != null)
    {
        <p>@TempData["notice"]</p>
    }
</div>
<div class="layout-content-body">
    <div class="row gutter-xs">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-actions">
                        <button type="button" class="card-action card-toggler" title="Collapse"></button>
                        <button type="button" class="card-action card-reload" title="Reload"></button>
                        <button type="button" class="card-action card-remove" title="Remove"></button>
                    </div>
                    <strong>نقش ها</strong>
                </div>

                <div class="card-body">

                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="md-form-group md-label-floating col-md-6">
                            <input class="md-form-control" type="text" name="name" id="serachInput" spellcheck="false" required="" aria-required="true">
                            <label class="md-control-label">جستجو</label>
                        </div>
                    </div>
                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="margin-top">
                            <div class="col-xs-6 col-md-6">
                                <a class="btn btn-primary marginbutoom" id="showcity" data-toggle="modal" asp-action="AddEditApplicationRole"
                                   data-target="#modal-action-application-role">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    افزودن نقش جدید
                                </a>
                            </div>
                        </div>
                    </div>
                    <table id="example" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>کد</th>
                                <th>نام نقش</th>
                                <th>توضیحات</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 1;
                                foreach (var item in Model)
                                {

                                    <tr>
                                        <td>@(i++)</td>
                                        <td>@item.Name</td>
                                        <td>@item.Description</td>


                                        <td>
                                            <a class="btn btn-info" id="editcity" data-toggle="modal" asp-action="AddEditApplicationRole"
                                               data-target="#modal-action-application-role" asp-route-Id="@item.Id">
                                                <i class="glyphicon glyphicon-pencil"></i>
                                                ویرایش
                                            </a>

                                            <a class="btn btn-danger" id="showcity" data-toggle="modal" asp-action="DeleteRole"
                                               data-target="#modal-action-application-role" asp-route-Id="@item.Id">
                                                <i class="glyphicon glyphicon-trash"></i>
                                                حذف
                                            </a>

                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="progress" class="addModal">
    <div class="addCenter">
        <img src="~/Content/loading.gif" />
    </div>
</div>
<div id="infoModalAlertColored" tabindex="-1" role="dialog" class="modal fade">

</div>
<div id="successModalAlert" tabindex="-1" role="dialog" class="modal fade">

</div>

@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-application-role", Size = ModalSize.Medium })

@section Scripts{
    <script src="~/js/modal-js/application-role-index.js"></script>
}